#!/usr/bin/env bash
# Regenerate committed integration artifacts for independent external clients:
#   abi/                      ABI JSON files required by the frontend
#   deployments/manifest.json versioned ABI and per-chain address manifest
# Per-chain addresses are generated by deploy scripts against an actual chain.
set -euo pipefail
cd "$(dirname "$0")/.."

MODE="publish"
if [ "${1:-}" = "--local" ] && [ "$#" -eq 1 ]; then
  MODE="local"
elif [ "$#" -ne 0 ]; then
  echo "usage: $0 [--local]" >&2
  exit 2
fi

CONTRACTS=(AssetRegistry EquiVault IERC20 IPriceOracle ISwapRouter RebalanceEngine VaultFactory)
STAGE_DIR="$(mktemp -d .artifact-stage.XXXXXX)"
STAGED_ABI="$STAGE_DIR/abi"
STAGED_MANIFEST="$STAGE_DIR/manifest.json"
OUTPUT_ABI="abi"
OUTPUT_MANIFEST="deployments/manifest.json"
WORKING_TREE_FINGERPRINT=""

cleanup() {
  rm -rf "$STAGE_DIR"
}
trap cleanup EXIT

if [ "$MODE" = "publish" ]; then
  git diff --quiet || {
    echo "refusing to publish artifacts from a working tree with uncommitted changes" >&2
    exit 1
  }
  git diff --cached --quiet || {
    echo "refusing to publish artifacts from an index with uncommitted changes" >&2
    exit 1
  }
else
  OUTPUT_ABI=".local-demo/artifacts/abi"
  OUTPUT_MANIFEST=".local-demo/artifacts/manifest.json"
  WORKING_TREE_FINGERPRINT="$(python3 - <<'PY'
import hashlib
import subprocess
from pathlib import Path

digest = hashlib.sha256()
digest.update(subprocess.check_output(["git", "diff", "--binary", "HEAD"]))
for raw_path in subprocess.check_output(["git", "ls-files", "--others", "--exclude-standard", "-z"]).split(b"\0"):
    if not raw_path:
        continue
    path = Path(raw_path.decode())
    digest.update(raw_path)
    digest.update(b"\0")
    digest.update(path.read_bytes())
print(digest.hexdigest())
PY
)"
fi
forge build
COMMIT="$(git rev-parse --verify HEAD^{commit})"
DATE="$(date -u +%Y-%m-%d)"
mkdir -p "$STAGED_ABI"

for contract in "${CONTRACTS[@]}"; do
  source_artifact="out/$contract.sol/$contract.json"
  [ -f "$source_artifact" ] || {
    echo "missing required artifact: $source_artifact" >&2
    exit 1
  }
  python3 - "$source_artifact" "$STAGED_ABI/$contract.json" <<'PY'
import json
import sys

with open(sys.argv[1], encoding="utf-8") as source:
    abi = json.load(source).get("abi")
if not isinstance(abi, list) or not abi:
    raise SystemExit(f"no ABI array in {sys.argv[1]}")
with open(sys.argv[2], "w", encoding="utf-8") as destination:
    json.dump(abi, destination, indent=2)
    destination.write("\n")
print(f"  abi/{sys.argv[2].split('/')[-1]} ({len(abi)} entries)")
PY
done

python3 - "$COMMIT" "$DATE" "$STAGED_ABI" "$STAGED_MANIFEST" "$MODE" "$WORKING_TREE_FINGERPRINT" <<'PY'
import json
import os
import sys

commit, date, abi_dir, manifest_path, mode, fingerprint = sys.argv[1:]
abi_files = sorted(f for f in os.listdir(abi_dir) if f.endswith(".json"))
manifest = {
    "schema": "equivaults-integration-artifacts/v1",
    "contractsCommit": commit,
    "generatedAt": date,
    "abiDir": "abi",
    "abiFiles": abi_files,
    "chains": {
        "31337": {
            "addressesFile": "deployments/31337/addresses.json",
            "network": "anvil-local",
            "note": "Regenerate with: anvil --chain-id 31337 && forge script script/DeployLocal.s.sol --rpc-url http://127.0.0.1:8545 --broadcast --unlocked --sender 0xf39Fd6e51aad88F6F4ce6aB8827279cffFb92266 --slow && python3 script/export-addresses.py",
        }
    },
    "note": "Regenerate ABI and manifest after any contract change: ./script/export-artifacts.sh",
}
if mode == "local":
    manifest["localWorkingTree"] = True
    manifest["source"] = {"baseCommit": commit, "workingTreeFingerprint": fingerprint}
    manifest["note"] = (
        "Local working-tree artifacts only; do not publish. Regenerate with: "
        "./script/export-artifacts.sh --local"
    )
with open(manifest_path, "w", encoding="utf-8") as destination:
    json.dump(manifest, destination, indent=2)
    destination.write("\n")
print(f"  deployments/manifest.json (commit {commit}, {len(abi_files)} ABI files)")
PY

mkdir -p "$(dirname "$OUTPUT_ABI")" "$(dirname "$OUTPUT_MANIFEST")"
if [ -d "$OUTPUT_ABI" ]; then
  mv "$OUTPUT_ABI" "$STAGE_DIR/previous-abi"
fi
if [ -f "$OUTPUT_MANIFEST" ]; then
  mv "$OUTPUT_MANIFEST" "$STAGE_DIR/previous-manifest.json"
fi
if ! mv "$STAGED_ABI" "$OUTPUT_ABI" || ! mv "$STAGED_MANIFEST" "$OUTPUT_MANIFEST"; then
  rm -rf "$OUTPUT_ABI" "$OUTPUT_MANIFEST"
  [ ! -d "$STAGE_DIR/previous-abi" ] || mv "$STAGE_DIR/previous-abi" "$OUTPUT_ABI"
  [ ! -f "$STAGE_DIR/previous-manifest.json" ] || mv "$STAGE_DIR/previous-manifest.json" "$OUTPUT_MANIFEST"
  exit 1
fi

if [ "$MODE" = "local" ]; then
  echo "Done: local-only ABI and manifest updated under .local-demo/artifacts/."
else
  echo "Done: abi/ and deployments/manifest.json updated."
fi
