#!/usr/bin/env bash
# Regenerate committed integration artifacts for independent external clients:
#   abi/                      ABI JSON files required by the frontend
#   deployments/manifest.json versioned ABI and per-chain address manifest
# Per-chain addresses are generated by deploy scripts against an actual chain.
set -euo pipefail
cd "$(dirname "$0")/.."

CONTRACTS=(AssetRegistry EquiVault IERC20 IPriceOracle ISwapRouter RebalanceEngine VaultFactory)
STAGE_DIR="$(mktemp -d .artifact-stage.XXXXXX)"
STAGED_ABI="$STAGE_DIR/abi"
STAGED_MANIFEST="$STAGE_DIR/manifest.json"

cleanup() {
  rm -rf "$STAGE_DIR"
}
trap cleanup EXIT

git diff --quiet || {
  echo "refusing to publish artifacts from a working tree with uncommitted changes" >&2
  exit 1
}
git diff --cached --quiet || {
  echo "refusing to publish artifacts from an index with uncommitted changes" >&2
  exit 1
}
forge build
COMMIT="$(git rev-parse --verify HEAD^{commit})"
DATE="$(date -u +%Y-%m-%d)"
mkdir -p "$STAGED_ABI"

for contract in "${CONTRACTS[@]}"; do
  source_artifact="out/$contract.sol/$contract.json"
  [ -f "$source_artifact" ] || {
    echo "missing required artifact: $source_artifact" >&2
    exit 1
  }
  python3 - "$source_artifact" "$STAGED_ABI/$contract.json" <<'PY'
import json
import sys

with open(sys.argv[1], encoding="utf-8") as source:
    abi = json.load(source).get("abi")
if not isinstance(abi, list) or not abi:
    raise SystemExit(f"no ABI array in {sys.argv[1]}")
with open(sys.argv[2], "w", encoding="utf-8") as destination:
    json.dump(abi, destination, indent=2)
    destination.write("\n")
print(f"  abi/{sys.argv[2].split('/')[-1]} ({len(abi)} entries)")
PY
done

python3 - "$COMMIT" "$DATE" "$STAGED_ABI" "$STAGED_MANIFEST" <<'PY'
import json
import os
import sys

commit, date, abi_dir, manifest_path = sys.argv[1:]
abi_files = sorted(f for f in os.listdir(abi_dir) if f.endswith(".json"))
manifest = {
    "schema": "equivaults-integration-artifacts/v1",
    "contractsCommit": commit,
    "generatedAt": date,
    "abiDir": "abi",
    "abiFiles": abi_files,
    "chains": {
        "31337": {
            "addressesFile": "deployments/31337/addresses.json",
            "network": "anvil-local",
            "note": "Regenerate with: anvil --chain-id 31337 && forge script script/DeployLocal.s.sol --rpc-url http://127.0.0.1:8545 --broadcast --unlocked --sender 0xf39Fd6e51aad88F6F4ce6aB8827279cffFb92266 --slow && python3 script/export-addresses.py",
        }
    },
    "note": "Regenerate ABI and manifest after any contract change: ./script/export-artifacts.sh",
}
with open(manifest_path, "w", encoding="utf-8") as destination:
    json.dump(manifest, destination, indent=2)
    destination.write("\n")
print(f"  deployments/manifest.json (commit {commit}, {len(abi_files)} ABI files)")
PY

mkdir -p deployments
if [ -d abi ]; then
  mv abi "$STAGE_DIR/previous-abi"
fi
if [ -f deployments/manifest.json ]; then
  mv deployments/manifest.json "$STAGE_DIR/previous-manifest.json"
fi
if ! mv "$STAGED_ABI" abi || ! mv "$STAGED_MANIFEST" deployments/manifest.json; then
  rm -rf abi deployments/manifest.json
  [ ! -d "$STAGE_DIR/previous-abi" ] || mv "$STAGE_DIR/previous-abi" abi
  [ ! -f "$STAGE_DIR/previous-manifest.json" ] || mv "$STAGE_DIR/previous-manifest.json" deployments/manifest.json
  exit 1
fi

echo "Done: abi/ and deployments/manifest.json updated."
